### ISSUE TITLE
Pequena modificação

### ISSUE THREAD

**Issue by danilozagatto** [ccmenezes/PageObjectsSelenium#1]
Olá Ccmenezes, tudo bom? 

Primeiramente adorei o seu projeto exemplo para a galera que está começando, acho isso bem legal, no seu código, vi uma  pequena melhoria que pode ser feita no método:

`public boolean verifyButton1() ` 

Você poderia colocar o return diretamente no `webElement.isEnable();` pois como ele retorna um boolean, economizaria linhas de código e daria uma maior elegância e legilibilidade. 

Ficaria assim 

` public boolean verifyButton1() {
	return button1.isEnabled();
 }`

Outra coisa, eu trabalho com Selenium a uns dois anos e meio e sempre tive vontade de escrever um blog sobre Selenium, automação e afins e percebi que você gosta de automação de testes e trabalha na area, você teria interesse em projetos nesse estilo ? 

Caso queira conversar a respeito, será um prazer trocar "figurinhas" sobre automação de testes, valeeeu abraço

**Comment by ccmenezes** [comment]
Olá Danilo, 
Muito obrigada pela sua ajuda, já fiz a refatoração que você propôs e fiquei bem empolgada com a ideia do blog, vamos conversando, me envie seus contatos para claudiacm.ti@gmail.com para que possamos conversar melhor. Abraços!
